# ondrejsika.com jekyll config
name: ondrejsika.com
markdown: redcarpet
future: false
exclude: [edit, ]
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
